# yamllint disable rule:braces rule:commas rule:colons rule:comments-indentation
---
window:
    # Blank space added around the window in pixels
    padding:
        x: 0
        y: 0

    # Spread additional padding evenly around the terminal content
    dynamic_padding: true

    # Disable border and title bar
    decorations: none

font:
    normal:
        family: SauceCodePro Nerd Font
        style: Regular
    bold:
        family: SauceCodePro Nerd Font
        style: Bold
    italic:
        family: SauceCodePro Nerd Font
        style: Italic

    # Point size of the font
    size: 11.5

# Colors (One Dark); if dim colors are not set, they will be calculated
# automatically based on the `normal` colors
colors:
    primary:
        background: '#24272e'
        foreground: '#abb2bf'
    cursor:
        text: '#0b0b0b'    # black
        cursor: '#528bff'
    vi_mode_cursor:
        text: '#abb2bf'
        cursor: '#333841'
    selection:
        text: '#abb2bf'
        background: '#3e4452'
    search:
        matches:
            foreground: '#3e4452'
            background: '#e5c07b'
        bar:
            background: '#282c34'
            foreground: '#abb2bf'
    normal:
        black:   '#24272e'
        red:     '#e06c75'
        green:   '#98c379'
        yellow:  '#e5c07b'
        blue:    '#61afef'
        magenta: '#c678dd'
        cyan:    '#56b6c2'
        white:   '#abb2bf'
    bright:
        black:   '#3e4452'
        red:     '#be5046'
        green:   '#98c379'
        yellow:  '#d19a66'
        blue:    '#61afef'
        magenta: '#c678dd'
        cyan:    '#56b6c2'
        white:   '#5c6370'

mouse:
    hide_when_typing: true
    url:
        # These are the modifiers that need to be held down for opening URLs
        # when clicking
        modifiers: Shift

selection:
    # When set to `true`, selected text will be copied to the primary
    # clipboard.
    save_to_clipboard: true

cursor:
    # Thickness of the cursor (number from `0.0` to `1.0`)
    thickness: 0.18
    # Vi mode cursor style
    vi_mode_style: Block

# Default shell
# For osx uncomment the following
    # shell:
        # program: /usr/local/bin/bash  # osx
    # args:
    # - --login

# Key bindings
key_bindings:
    - { key: V,        mods: Super, action: Paste                }
    - { key: C,        mods: Super, action: Copy                 }
    - { key: Q,        mods: Super, action: Quit                 }
    - { key: W,        mods: Super, action: Quit                 }
    - { key: Equals,   mods: Super, action: IncreaseFontSize     }
    - { key: Subtract, mods: Super, action: DecreaseFontSize     }
    - { key: Key0,     mods: Super, action: ResetFontSize        }
    - { key: End,      mods: Shift, action: ScrollToBottom       }
    - { key: Home,     mods: Shift, action: ScrollToTop          }
    # Since we cannot set zoom factor we bind keys multiple times
    - { key: U,        mods: Super, action: IncreaseFontSize     }
    - { key: U,        mods: Super, action: IncreaseFontSize     }
    - { key: U,        mods: Super, action: IncreaseFontSize     }
    - { key: U,        mods: Super, action: IncreaseFontSize     }
    - { key: U,        mods: Super, action: IncreaseFontSize     }
    - { key: U,        mods: Super, action: IncreaseFontSize     }
    - { key: U,        mods: Super, action: IncreaseFontSize     }
    - { key: U,        mods: Super, action: IncreaseFontSize     }
    - { key: U,        mods: Super, action: IncreaseFontSize     }
    - { key: U,        mods: Super, action: IncreaseFontSize     }
    - { key: U,        mods: Super, action: IncreaseFontSize     }
    - { key: U,        mods: Super, action: IncreaseFontSize     }
    - { key: U,        mods: Super, action: IncreaseFontSize     }
    - { key: U,        mods: Super, action: IncreaseFontSize     }
    - { key: U,        mods: Super, action: IncreaseFontSize     }
    - { key: U,        mods: Super, action: IncreaseFontSize     }
    - { key: U,        mods: Super, action: IncreaseFontSize     }
    - { key: U,        mods: Super, action: IncreaseFontSize     }
    - { key: D,        mods: Super, action: DecreaseFontSize     }
    - { key: D,        mods: Super, action: DecreaseFontSize     }
    - { key: D,        mods: Super, action: DecreaseFontSize     }
    - { key: D,        mods: Super, action: DecreaseFontSize     }
    - { key: D,        mods: Super, action: DecreaseFontSize     }
    - { key: D,        mods: Super, action: DecreaseFontSize     }
    - { key: D,        mods: Super, action: DecreaseFontSize     }
    - { key: D,        mods: Super, action: DecreaseFontSize     }
    - { key: D,        mods: Super, action: DecreaseFontSize     }
    - { key: D,        mods: Super, action: DecreaseFontSize     }
    - { key: D,        mods: Super, action: DecreaseFontSize     }
    - { key: D,        mods: Super, action: DecreaseFontSize     }
    - { key: D,        mods: Super, action: DecreaseFontSize     }
    - { key: D,        mods: Super, action: DecreaseFontSize     }
    - { key: D,        mods: Super, action: DecreaseFontSize     }
    - { key: D,        mods: Super, action: DecreaseFontSize     }
    - { key: D,        mods: Super, action: DecreaseFontSize     }
    - { key: D,        mods: Super, action: DecreaseFontSize     }
    # Vi mode
    - { key: LBracket, mods: Control|Alt,  action: ToggleViMode  }
    - { key: Q,        mode: Vi,           action: ToggleViMode  }
    - { key: H,        mods: Shift, mode: Vi,  action: First     }
    - { key: L,        mods: Shift, mode: Vi,  action: Last      }
    # Tmux-like
    - { key: P,        mods: Control|Alt,  action: Paste         }
    # On OSX uncomment the following to enable alt maps
    # - { key: D,        mods: Alt,   chars: "\x1bd"               }
    # - { key: Z,        mods: Alt,   chars: "\x1bz"               }
...
